### ISSUE TITLE
ntscvideo using interlaced mode, jumps randomly between frames

### ISSUE THREAD

**Issue by ghost** [LMP88959/NTSC-CRT#37] opened 2023-10-17 14:54 UTC
Steps to recreate:
1. ./ffmpeg -i video.mp4 -r 30 -s 640x480 frames/%06d.bmp
2. ./ntscvideo -o 200 640 480 24
3. ./ffmpeg -y -r 30 -i output/%06d.bmp output.mp4

For some reason, it likes to randomly jump between frames in interlaced mode. It doesn't do this in progressive mode.

**Comment by LMP88959** [comment] 2023-10-17 15:27
Thank you for taking time to make this issue!
This is a 'feature' not a bug, haha. It's the fact that there is a lot of noise in the signal (you give it 24 as the noise value) that is causing the video to lose track of vertical sync every once in a while.

A solution:
Change CRT_DO_VSYNC to 0 in crt_core.h and recompile the ntscvideo app, this will prevent VSYNC from getting lost. Let me know if that solves your problem :)

**Comment by ghost** [comment] 2023-10-17 16:48
It's doing the same thing even after I changed CRT_DO_VSYNC

**Comment by LMP88959** [comment] 2023-10-17 17:26
Hmm, it's not doing it for me, are you sure you recompiled everything?

**Comment by ghost** [comment] 2023-10-18 13:34
Just confirmed that I correctly re-compiled everything.
It's still doing it

**Comment by LMP88959** [comment] 2023-10-18 15:33
Thanks for confirming, is it possible for you to describe the problem you are seeing in more detail? I'm not sure what you mean by 'jumps randomly between frames,' is the video stuttering?

EDIT: Nevermind I'm finally able to reproduce it. I'll begin working on figuring out what's wrong with it and get back to you.

**Comment by LMP88959** [comment] 2023-10-18 16:10
That was a tricky one, thanks again for finding the issue. I just committed a fix to main, let me know if it works for you.

**Comment by ghost** [comment] 2023-10-18 22:00
That Fixed the problem!

**Closed as completed** 2023-10-19 01:56 UTC
